- phalcon-migrations
Autoloader isn't found when installing composer package.
> Autoloader not found when require package in project

- src/Migrations.php
> CreateTable failed due to changed interface.

- composer.json
- composer.lock
- src/Migrations.php
- src/Mvc/Model/Migration.php
- tests/Helpers.php
- tests/Integration/IntegrationTestCase.php
- tests/Integration/MigrationsTest.php
> #22 - Fix unnecessary table alter due DATE and DATETIME columns

- src/Migrations.php
- src/Mvc/Model/Migration.php
- tests/Integration/ColumnTypesTest.php
- tests/Integration/IntegrationTestCase.php
> #8 - Column type time

- tests/Integration/ColumnTypesTest.php
> #3 - Add test coverage for MySQL JSON column type

- README.md
> #35 - Update docs

- src/Mvc/Model/Migration.php
- tests/Integration/PostgreSQL/IssuesTest.php
Issue - #1
```sql
CREATE TABLE "table" (
"id" INTEGER NOT NULL,
PRIMARY KEY ("id")
);
```
Which generates current code
```
$this->morphTable('table', [
'columns' => [
new Column(
'id',
[
'type' => Column::TYPE_INTEGER,
'primary' => true,
'notNull' => true,
'first' => true
])
],
]
);
```
> #1 - Fix primary key index

- src/Console/Commands/Builtin/Migration.php
> #39 - Add condition to check from config file

- src/Migrations.php
> #40 - Fix notice with cleanup

- src/Mvc/Model/Migration.php
> #49 - Update array of columns without size

- src/Mvc/Model/Migration.php
- tests/Integration/MySQL/ColumnTypesTest.php
> #51 - Fix generation of null columns

- src/Migrations.php
- tests/Integration/MySQL/ColumnTypesTest.php
- tests/Integration/MySQL/TimestampedVersionTest.php
- tests/Integration/PostgreSQL/ColumnTypesTest.php
- tests/Integration/PostgreSQL/IssuesTest.php
> #53 - Fix running timestamp based migrations

- .github/workflows/validations.yml
- src/Mvc/Model/Migration.php
- tests/Integration/MySQL/ColumnTypesTest.php
- tests/var/issues/29/0.1.0/task_jobs.php
> #7 - Add support of ENUM column type

- .github/workflows/tests.yml
- .github/workflows/validations.yml
Update shivammathur/setup-php to `v2` and add cache for extensions.
> Speed up Workflows

- src/Mvc/Model/Migration.php
> #57 - Set default value to skip AUTO_INCREMENT option

- box.json
- composer.json
- composer.lock
> #12 - Phalcon migrations phar

- .github/workflows/release-phar.yml
> #12 - Implement release-phar.yml

- src/Migrations.php
- tests/Integration/MigrationsTest.php
- tests/var/issues/66/0.0.1/issue66.php
- tests/var/issues/66/0.0.2/issue66.php
- tests/var/issues/66/0.0.3/issue66.php
- tests/var/issues/66/0.0.4/issue66.php
> #66 - Fixed running missed in between migrations

- psalm.xml.dist
- src/Console/Commands/Migration.php
- src/Migration/Action/Generate.php
- src/Migrations.php
- src/Mvc/Model/Migration.php
- tests/cli/GenerateCest.php
- tests/integration/Migration/Action/GenerateCest.php
> #68 - Added new option to ignore referenced schema

- src/Migration/Action/Generate.php
> support column comment

- CHANGELOG.md
- composer.json
- composer.lock
- src/Generator/Snippet.php
- src/Migration/Action/Generate.php
- src/Migrations.php
- src/Mvc/Model/Migration.php
- src/Utils/Helper.php
Hello!
* Type: code quality
* Link to issue: #90
**In raising this pull request, I confirm the following (please check boxes):**
Small description of change:
Migrations code generator changed from `Phalcon\Migrations\Generator\Snippet` to `nette/php-generator`
Thanks
[:contrib:]: https://github.com/phalcon/migrations/blob/master/CONTRIBUTING.md
> FEATURE-90: Added new code generator
